# Generated by Django 4.1.7 on 2023-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selectedCountry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
