# Generated by Django 4.1.7 on 2023-03-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_selectedcountry_post_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='lotArea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
