# Generated by Django 4.1.7 on 2023-03-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_listing_image'),
        ('post', '0007_remove_post_fstfloorarea_remove_post_sndfloorarea_and_more'),
    ]

    operations = [
    ]
