# Generated by Django 4.1.6 on 2023-02-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisaldata',
            name='images',
        ),
        migrations.AddField(
            model_name='appraisaldata',
            name='images',
            field=models.ManyToManyField(related_name='images', to='api.image'),
        ),
    ]
