# Generated by Django 4.1.6 on 2023-02-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_remove_appraisaldata_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisaldata',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='appraisaldata',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
