# Generated by Django 4.1.6 on 2023-02-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appraisaldata_images_delete_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAppraisalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='AppraisalData',
        ),
    ]
