# Generated by Django 4.1.6 on 2023-02-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rawappraisaldata_delete_appraisaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawappraisaldata',
            name='images',
        ),
    ]
