# Generated by Django 4.1.6 on 2023-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_rawappraisaldata_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='api_images')),
            ],
        ),
        migrations.DeleteModel(
            name='RawAppraisalData',
        ),
    ]
