#ColumnNames.py


ColumnNames = ("ID", "AREA", "SALEPRICE", "ZONING", "LOTAREA", "UTILITIES", "NEIGHBORHOOD", "BLDGTYPE", "HOUSESTYLE", "OVERALLQUAL",
                    "OVERALLCOND", "YEARBUILT", "YEARREMOD", "EXTERIOR1", "EXTERQUAL", "EXTERCOND", "FOUNDATION", "BSMTFIN1", "BSMTFINSF1",
                    "TOTALBSMTSF", "HEATING", "HEATINGQC", "CENTRALAIR", "ELECTRICAL", "FIRSTFLOORSF", "SECONDFLOORSF", "FULLBATH", "HALFBATH",
                    "BEDROOM", "KITCHEN", "KITCHENQUAL", "TOTRMSABVGRADE", "GARAGETYPE", "GARAGECARS", "GARAGEAREA", "GARAGEQUAL", "WOODDECKSF", "FENCE")