#Created to setup the database for REAML
import os 
import sqlite3
print(sqlite3.sqlite_version)

connection = sqlite3.connect( os.getcwd() + '\\backend\database\DBInterface\comps.db' )

print( "Connected to database successfully.\n" )

# may need to remove some columns (at least temporarily) for simplicity's sake
# TODO finish constraining the required columns
connection.execute("""CREATE TABLE IF NOT EXISTS Comps ( 
ID INT PRIMARY KEY NOT NULL, 
SQFT INT NOT NULL CHECK (SQFT >= 0),
PRICE INT NOT NULL CHECK (PRICE >= 0),
SUBCLASS TEXT,
ZONING TEXT,
LOTFRONTAGE INT,
LOTAREA INT,
STREET TEXT,
ALLEY TEXT,
LOTSHAPE TEXT,
LANDCONTOUR TEXT,
UTILITIES TEXT,
LOTCONFIG TEXT,
LANDSLOPE TEXT,
NEIGHBORHOOD TEXT,
COND1 TEXT,
COND2 TEXT,
BLDGTYPE TEXT,
HOUSESTYLE TEXT,
OVERALLQUAL INT CHECK ( OVERALLQUAL <= 10 AND OVERALLQUAL > 0 ),
OVERALLCOND INT CHECK ( OVERALLCOND <= 10 AND OVERALLCOND > 0 ),
YEARBUILT INT CHECK ( julianday(YEARBUILT) <= julianday() ),
YEARREMOD INT CHECK ( julianday(YEARREMOD) <= julianday() AND YEARREMOD >= YEARBUILT ),
ROOFSTYLE TEXT,
ROOTMATL TEXT,
EXTERIOR1 TEXT,
EXTERIOR2 TEXT,
MASVNRTYPE TEXT,
MASVNRAREA REAL CHECK (MASVNRAREA > 0),
EXTERQUAL TEXT,
EXTERCOND TEXT,
FOUNDATION TEXT,
BSMTQUAL TEXT,
BSMTCOND TEXT, 
BMSTEXPOSURE TEXT,
BMSTFIN1 TEXT,
BSMTFINSF1 REAL CHECK( BSMTFINSF1 >= 0 ),
BSMTFIN2 TEXT,
BSMTFINSF2 REAL CHECK(BSMTFINSF2 >= 0 ),
BSMTUNFSF REAL CHECK(BSMTUNFSF >= 0),
TOTALBSMTSF REAL CHECK( TOTALBSMTSF >= 0),
HEATING TEXT,
HEATINGQC TEXT,
CENTRALAIR BOOL,
ELECTRICAL TEXT,
FIRSTFLOORSF REAL CHECK( FIRSTFLOORSF >= 0),
SECONDFLOORSF REAL CHECK(SECONDFLOORSF >= 0),
LOWQUALFINSF REAL CHECK(LOWQUALFINSF >= 0),
GRLIVAREA REAL CHECK(GRLIVAREA >= 0),
BSMTFULLBATH INT,
BSMTHALFBATH INT,
FULLBATH INT,
HALFBATH INT,
BEDROOM INT,
KITCHEN INT,
KITCHENQUAL TEXT,
TOTRMSABVGRADE INT,
FUNCTIONAL TEXT,
FIREPLACES INT,
FIREPLACEQUAL TEXT,
GARAGETYPE TEXT,
GARAGEYRBUILT INT,
GARAGEFINISH TEXT,
GARAGECARS INT,
GARAGEAREA REAL,
GARAGEQUAL TEXT,
GARAGECOND TEXT,
PAVEDDRIVE CHAR,
WOODDECKSF REAL,
OPENPORCHSF REAL,
ENCLOSEDPORCH REAL,
PORCH REAL,
SCREENPORCH REAL,
POOLAREA REAL,
POOLQC TEXT,
FENCE TEXT,
MISCFEATURE TEXT,
MISCVAL REAL,
MOSOLD INT,
YRSOLD INT,
SALETYPE TEXT,
SALECOND TEXT,
SALEPRICE REAL);""")

# Creating cursor object using connection object - check that the columns were created correctly
cursor = connection.cursor()
cursor.execute( "PRAGMA table_info('Comps')")
print(cursor.fetchall())

print("done.\n")
