#ColumnNames.py


ColumnNames = ("ID", "AREA", "SALEPRICE", "ZONING", "LOTAREA", "UTILITIES", "NEIGHBORHOOD", "BLDGTYPE", "HOUSESTYLE", "OVERALLQUAL",
                    "OVERALLCOND", "YEARBUILT", "YEARREMOD", "EXTERIOR1", "EXTERQUAL", "EXTERCOND", "FOUNDATION", "BSMTFIN1", "BSMTFINSF1",
                    "TOTALBSMTSF", "HEATING", "HEATINGQC", "CENTRALAIR", "ELECTRICAL", "FULLBATH", "HALFBATH",
                    "BEDROOM", "KITCHEN", "KITCHENQUAL", "TOTRMSABVGRADE", "GARAGETYPE", "GARAGECARS", "GARAGEAREA", "GARAGEQUAL", "WOODDECKSF", "FENCE")

dict_keys = [
    "id", 
    "area", 
    "price",
    "zone", 
    "lotArea", 
    "utilities", 
    "neighborhood", 
    "bldgType", 
    "houseStyle", 
    "overallQual",
    "overallCond",
    "yearBuilt", 
    "yearRemod",
    "exterior1", 
    "exterQual", 
    "exterCond", 
    "foundation", 
    "bsmtFinType1", 
    "bsmtFindSF1",
    "totalBsmtSF", 
    "heating", 
    "heatingQC", 
    "centralAir", 
    "electrical", 
    "fullBath", 
    "halfBath",
    "bedroom", 
    "kitchen", 
    "kitchenQual", 
    "totRmsAbvGrd", 
    "garageType", 
    "garageCars", 
    "garageArea", 
    "garageQual", 
    "woodDeckSF", 
    "fence"]