# Generated by Django 4.1.3 on 2023-01-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0003_image_description_image_image_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
