# Generated by Django 4.1.3 on 2023-01-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0005_imagealbum_alter_image_description_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
        ),
    ]
