# Generated by Django 4.1.3 on 2023-01-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0006_alter_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dj_test_app.imagealbum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='album',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='model', to='dj_test_app.imagealbum'),
        ),
    ]
