# Generated by Django 4.1.3 on 2023-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0007_image_album_imagealbum_name_alter_listing_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(default='Default album name', max_length=255),
        ),
    ]
