# Generated by Django 4.1.3 on 2023-01-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0008_alter_imagealbum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='album',
        ),
    ]
