# Generated by Django 4.1.3 on 2023-01-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0009_remove_listing_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='album',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='model', to='dj_test_app.imagealbum'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default='Default album id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dj_test_app.imagealbum'),
        ),
    ]
