# Generated by Django 4.1.3 on 2023-01-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test_app', '0014_remove_image_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dj_test_app.imagealbum'),
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
        ),
    ]
